# TCL File Generated by Component Editor 13.0
# Sat Nov 03 18:01:28 EDT 2012
# DO NOT MODIFY


#
# stamp "stamp" v1.0
# A.E. LaBarge 2013.12.03.18:01:28
#
#

#
# request TCL package from ACDS 13.0
#
package require -exact qsys 13.0


#
# module avl_sysid
#
set_module_property NAME stamp
set_module_property VERSION 22.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Omniware
set_module_property AUTHOR "A. LaBarge"
set_module_property DISPLAY_NAME "System ID, Version, and Date & Time"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


#
# file sets
#
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL stamp_top
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file stamp_top.vhd VHDL PATH stamp_top.vhd
add_fileset_file stamp_regs.vhd VHDL PATH stamp_regs.vhd

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL stamp_top
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file stamp_top.vhd VHDL PATH stamp_top.vhd
add_fileset_file stamp_regs.vhd VHDL PATH stamp_regs.vhd


#
# parameters
#


#
# display items
#


#
# connection point s1
#
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 2
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0

add_interface_port s1 read_n read_n Input 1
add_interface_port s1 write_n write_n Input 1
add_interface_port s1 address address Input 10
add_interface_port s1 readdata readdata Output 32
add_interface_port s1 writedata writedata Input 32

#
# connection point clk
#
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1

#
# connection point stamp_export
#
add_interface stamp_export conduit end
set_interface_property stamp_export associatedClock clk
set_interface_property stamp_export associatedReset reset
set_interface_property stamp_export ENABLED true

add_interface_port stamp_export tp export Output 4

#
# DTS Entry
#
set_module_assignment embeddedsw.dts.vendor "omni"
set_module_assignment embeddedsw.dts.group "stamp"
set_module_assignment embeddedsw.dts.name "stamp"
set_module_assignment embeddedsw.dts.compatible "generic-uio"

