# TCL File Generated by Component Editor 12.0sp2
# Sat Nov 03 18:01:28 EDT 2012
# DO NOT MODIFY


#
# com_com "com" v1.0
# A.E. LaBarge 2012.11.03.18:01:28
#
#

#
# request TCL package from ACDS 12.0
#
package require -exact qsys 12.0


#
# module com_232h
#
set_module_property NAME com
set_module_property VERSION 22.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Omniware
set_module_property AUTHOR "A.E. LaBarge"
set_module_property DISPLAY_NAME "Serial COM w/ Head & Tail"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


#
# file sets
#
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL com_top
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file com_top.vhd VHDL PATH com_top.vhd
add_fileset_file com_regs.vhd VHDL PATH com_regs.vhd
add_fileset_file com_ctl.vhd VHDL PATH com_ctl.vhd
add_fileset_file com_irq.vhd VHDL PATH com_irq.vhd
add_fileset_file com_rx.vhd VHDL PATH com_rx.vhd
add_fileset_file com_tx.vhd VHDL PATH com_tx.vhd
add_fileset_file com_2K.vhd VHDL PATH com_2k.vhd
add_fileset_file com_burst.vhd VHDL PATH com_burst.vhd

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL com_top
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS true
add_fileset_file com_top.vhd VHDL PATH com_top.vhd
add_fileset_file com_regs.vhd VHDL PATH com_regs.vhd
add_fileset_file com_ctl.vhd VHDL PATH com_ctl.vhd
add_fileset_file com_irq.vhd VHDL PATH com_irq.vhd
add_fileset_file com_rx.vhd VHDL PATH com_rx.vhd
add_fileset_file com_tx.vhd VHDL PATH com_tx.vhd
add_fileset_file com_2K.vhd VHDL PATH com_2k.vhd
add_fileset_file com_burst.vhd VHDL PATH com_burst.vhd


#
# parameters
#


#
# display items
#


#
# connection point s1
#
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 2
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true

add_interface_port s1 read_n read_n Input 1
add_interface_port s1 write_n write_n Input 1
add_interface_port s1 address address Input 12
add_interface_port s1 readdata readdata Output 32
add_interface_port s1 writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


#
# connection point m1
#
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock clk
set_interface_property m1 associatedReset reset
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true

add_interface_port m1 m1_read read Output 1
add_interface_port m1 m1_rd_address address Output 32
add_interface_port m1 m1_readdata readdata Input 32
add_interface_port m1 m1_rd_waitreq waitrequest Input 1
add_interface_port m1 m1_rd_burstcount burstcount Output 16
add_interface_port m1 m1_rd_datavalid readdatavalid Input 1


#
# connection point irq
#
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint s1
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset reset
set_interface_property irq ENABLED true

add_interface_port irq irq irq Output 1


#
# connection point clk
#
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1


#
# connection point com_export
#
add_interface com_export conduit end
set_interface_property com_export associatedClock clk
set_interface_property com_export associatedReset reset
set_interface_property com_export ENABLED true

add_interface_port com_export head_addr export Input 16
add_interface_port com_export tail_addr export Output 16

add_interface_port com_export rx_in export Input 1
add_interface_port com_export tx_out export Output 1
add_interface_port com_export test_bit export Output 1
add_interface_port com_export debug export Output 4

#
# DTS Entry
#
set_module_assignment embeddedsw.dts.vendor "omni"
set_module_assignment embeddedsw.dts.group "com"
set_module_assignment embeddedsw.dts.name "com"
set_module_assignment embeddedsw.dts.compatible "generic-uio"

